# Generated by Django 5.2.5 on 2025-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("actor1_name", models.CharField(max_length=100)),
                ("actor2_name", models.CharField(blank=True, max_length=100)),
                ("director_name", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
                ("release_year", models.PositiveIntegerField()),
            ],
        ),
    ]
